import os 

CONSUMER_KEY = os.getenv('ALLY_CONSUMER')
CONSUMER_SECRET = os.getenv('ALLY_CONSUMER_SECRET')
OAUTH_TOKEN = os.getenv('ALLY_OAUTH_TOKEN')
OAUTH_TOKEN_SECRET = os.getenv('ALLY_OAUTH_TOKEN_SECRET')